apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "invoicer.fullname" . }}-config
  labels:
    {{- include "invoicer.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ include "invoicer.databaseUrl" . | quote }}
  NEXTAUTH_URL: {{ .Values.config.nextauthUrl | quote }}
