apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "invoicer.fullname" . }}
  labels:
    {{- include "invoicer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "invoicer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "invoicer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.port }}
        envFrom:
        - configMapRef:
            name: {{ include "invoicer.fullname" . }}-config
        - secretRef:
            name: {{ include "invoicer.fullname" . }}-secrets
        resources:
          {{- toYaml .Values.app.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.app.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.app.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
