apiVersion: v1
kind: Secret
metadata:
  name: {{ include "invoicer.fullname" . }}-secrets
  labels:
    {{- include "invoicer.labels" . | nindent 4 }}
type: Opaque
data:
  NEXTAUTH_SECRET: {{ .Values.secret.nextauthSecret | quote }}
